"use client";
import { useState, useEffect, useCallback, useRef } from "react";
import {
  LayoutDashboard,ShoppingBag,ChefHat,UtensilsCrossed,Armchair,CalendarClock,
  Package,Users,BarChart3,Heart,Settings,LogOut,Bell,Search,Plus,Edit,Check,X,
  Clock,DollarSign,AlertTriangle,CreditCard,Banknote,Receipt,ArrowUpRight,
  ArrowDownRight,Phone,Mail,Star,Flame,Volume2,Grid3X3,List,RefreshCw,
  PanelLeftClose,PanelLeft,CircleDot,Square,Circle,CheckCircle2,XCircle,Info,
  ShieldCheck,Lock,KeyRound,UserCog,Store,Globe,Target,TrendingDown,EyeOff,Eye,
  Wifi,WifiOff,Trash2,Save,Leaf,Wine,Beef,Cake,Coffee,Salad,Pizza,Soup,
  Zap,Activity,ChevronRight,ChevronDown,GripVertical,Timer,Hash,MapPin,
  Sparkles,Crown,Shield,Database,Server,Layers,Monitor,BarChart,PieChart
} from "lucide-react";
import {
  AreaChart,Area,BarChart as ReBarChart,Bar,PieChart as RePieChart,Pie,Cell,
  XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer
} from "recharts";

/* ━━━ Utilities ━━━ */
function cn(...c){return c.filter(Boolean).join(" ")}
function fmt(n){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n||0))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,9)}
function minsAgo(d){return Math.floor((Date.now()-new Date(d).getTime())/60000)}
function fmtTime(d){const m=minsAgo(d);return m<60?`${m}m ago`:`${Math.floor(m/60)}h ${m%60}m`}
function urgClass(d){const m=minsAgo(d);return m<10?"text-emerald-400":m<20?"text-amber-400":"text-red-400"}
const CAT_ICONS={c1:Leaf,c2:UtensilsCrossed,c3:Flame,c4:Beef,c5:Cake,c6:Wine};
const CAT_COLORS={c1:"#22c55e",c2:"#f59e0b",c3:"#ef4444",c4:"#8b5cf6",c5:"#ec4899",c6:"#06b6d4"};

/* ━━━ Seed Data ━━━ */
const seedCats=[{id:"c1",name:"Antipasti"},{id:"c2",name:"Pasta"},{id:"c3",name:"Pizza"},{id:"c4",name:"Secondi"},{id:"c5",name:"Dolci"},{id:"c6",name:"Bevande"}];
const seedMenu=[
  {id:"m1",name:"Bruschetta Classica",catId:"c1",price:8.9,cost:2.1,available:true,prepTime:8,calories:280,allergens:["Gluten","Dairy"],station:"salad"},
  {id:"m2",name:"Carpaccio di Manzo",catId:"c1",price:14.9,cost:5.2,available:true,prepTime:10,calories:220,allergens:[],station:"salad"},
  {id:"m3",name:"Insalata Caprese",catId:"c1",price:10.5,cost:3.1,available:true,prepTime:5,calories:310,allergens:["Dairy"],station:"salad"},
  {id:"m4",name:"Spaghetti Carbonara",catId:"c2",price:14.5,cost:3.2,available:true,prepTime:15,calories:520,allergens:["Gluten","Dairy","Egg"],station:"pasta"},
  {id:"m5",name:"Penne Arrabbiata",catId:"c2",price:12.9,cost:2.5,available:true,prepTime:12,calories:440,allergens:["Gluten"],station:"pasta"},
  {id:"m6",name:"Risotto ai Funghi Porcini",catId:"c2",price:16.9,cost:4.0,available:true,prepTime:20,calories:480,allergens:["Dairy"],station:"pasta"},
  {id:"m7",name:"Lasagna della Casa",catId:"c2",price:15.5,cost:3.8,available:false,prepTime:25,calories:620,allergens:["Gluten","Dairy"],station:"pasta"},
  {id:"m8",name:"Margherita D.O.P.",catId:"c3",price:11.9,cost:2.8,available:true,prepTime:12,calories:750,allergens:["Gluten","Dairy"],station:"pizza"},
  {id:"m9",name:"Diavola",catId:"c3",price:13.9,cost:3.4,available:true,prepTime:12,calories:820,allergens:["Gluten","Dairy"],station:"pizza"},
  {id:"m10",name:"Quattro Formaggi",catId:"c3",price:14.5,cost:4.2,available:true,prepTime:14,calories:900,allergens:["Gluten","Dairy"],station:"pizza"},
  {id:"m11",name:"Bistecca alla Fiorentina",catId:"c4",price:32.9,cost:12,available:true,prepTime:25,calories:650,allergens:[],station:"grill"},
  {id:"m12",name:"Branzino al Forno",catId:"c4",price:24.9,cost:8.5,available:true,prepTime:20,calories:380,allergens:["Fish"],station:"grill"},
  {id:"m13",name:"Tiramisu della Casa",catId:"c5",price:8.9,cost:2,available:true,prepTime:5,calories:420,allergens:["Gluten","Dairy","Egg"],station:"salad"},
  {id:"m14",name:"Panna Cotta ai Frutti",catId:"c5",price:7.9,cost:1.5,available:true,prepTime:3,calories:340,allergens:["Dairy"],station:"salad"},
  {id:"m15",name:"Espresso Doppio",catId:"c6",price:2.9,cost:0.4,available:true,prepTime:2,calories:5,allergens:[],station:"bar"},
  {id:"m16",name:"Chianti Classico Riserva",catId:"c6",price:8.5,cost:2.8,available:true,prepTime:1,calories:125,allergens:["Sulfites"],station:"bar"},
  {id:"m17",name:"Aperol Spritz",catId:"c6",price:9.5,cost:2.5,available:true,prepTime:3,calories:180,allergens:["Sulfites"],station:"bar"},
  {id:"m18",name:"Acqua Panna",catId:"c6",price:3.5,cost:0.3,available:true,prepTime:1,calories:0,allergens:[],station:"bar"},
];
const seedTables=[{id:"t1",number:"01",capacity:2,section:"Main"},{id:"t2",number:"02",capacity:4,section:"Main"},{id:"t3",number:"03",capacity:4,section:"Main"},{id:"t4",number:"04",capacity:6,section:"Main"},{id:"t5",number:"05",capacity:2,section:"Main"},{id:"t6",number:"06",capacity:4,section:"Main"},{id:"t7",number:"07",capacity:8,section:"Main"},{id:"t8",number:"P1",capacity:4,section:"Terrace"},{id:"t9",number:"P2",capacity:4,section:"Terrace"},{id:"t10",number:"B1",capacity:2,section:"Bar"},{id:"t11",number:"B2",capacity:2,section:"Bar"},{id:"t12",number:"VIP",capacity:10,section:"Private"}];
const seedInv=[{id:"i1",name:"Spaghetti",qty:12.5,unit:"kg",cost:2.4,threshold:5,par:20,supplier:"De Cecco",category:"Dry Goods"},{id:"i2",name:"Penne Rigate",qty:8.2,unit:"kg",cost:2.2,threshold:5,par:15,supplier:"De Cecco",category:"Dry Goods"},{id:"i3",name:"Mozzarella di Bufala",qty:4.8,unit:"kg",cost:12,threshold:3,par:8,supplier:"Latteria Sorrentina",category:"Dairy"},{id:"i4",name:"Parmigiano 24M",qty:2.1,unit:"kg",cost:28,threshold:2,par:5,supplier:"Latteria Sorrentina",category:"Dairy"},{id:"i5",name:"Beef Tenderloin AAA",qty:3.2,unit:"kg",cost:45,threshold:2,par:6,supplier:"Fleischer Huber",category:"Protein"},{id:"i6",name:"EVOO Ferraro",qty:8.5,unit:"L",cost:14,threshold:5,par:15,supplier:"Ferraro Imports",category:"Oils"},{id:"i7",name:"Fresh Basil",qty:0.3,unit:"kg",cost:18,threshold:0.5,par:1,supplier:"Local Farm",category:"Produce"},{id:"i8",name:"Chianti DOCG",qty:18,unit:"btl",cost:12,threshold:6,par:24,supplier:"Vinoteca",category:"Wine"}];
const seedStaff=[{id:"s1",name:"Marco Rossi",role:"Owner",rate:0,initials:"MR",active:true,email:"marco@bellacucina.de"},{id:"s2",name:"Anna Schmidt",role:"Manager",rate:22,initials:"AS",active:true,email:"anna@bellacucina.de"},{id:"s3",name:"Luigi Bianchi",role:"Head Chef",rate:20,initials:"LB",active:true,email:"luigi@bellacucina.de"},{id:"s4",name:"Sophie Weber",role:"Server",rate:14,initials:"SW",active:true,email:"sophie@bellacucina.de"},{id:"s5",name:"Felix Müller",role:"Cashier",rate:13,initials:"FM",active:true,email:"felix@bellacucina.de"},{id:"s6",name:"Emma Fischer",role:"Host",rate:13,initials:"EF",active:true,email:"emma@bellacucina.de"}];
const seedCust=[{id:"cu1",name:"Hans Klein",email:"hans.klein@email.de",phone:"+49 176 123 4567",visits:24,spent:1842.5,points:1840,tags:["VIP"],notes:"Prefers Table 04"},{id:"cu2",name:"Dr. Julia Braun",email:"j.braun@corp.de",phone:"+49 151 987 6543",visits:12,spent:2156,points:2150,tags:["VIP","Corporate"],notes:"Detailed invoices"},{id:"cu3",name:"Maria Costa",email:"m.costa@email.de",phone:"+49 172 888 7654",visits:8,spent:562.3,points:560,tags:["Dietary"],notes:"Nut allergy"}];
const seedRes=[{id:"rv1",name:"Klein Family",phone:"+49 176 123 4567",size:4,time:"18:30",date:"Today",tableId:"t4",status:"confirmed",notes:"Anniversary — prosecco"},{id:"rv2",name:"Dr. Braun",phone:"+49 151 987 6543",size:10,time:"19:00",date:"Today",tableId:"t12",status:"confirmed",notes:"Wine pairing"},{id:"rv3",name:"Schneider",phone:"+49 170 555 1234",size:2,time:"20:00",date:"Today",tableId:"t5",status:"confirmed",notes:""}];

/* ━━━ Premium UI Atoms ━━━ */
function Glass({children,className="",hover3d=false,onClick}){
  const ref=useRef(null);const[tf,setTf]=useState("");
  const move=e=>{if(!hover3d||!ref.current)return;const r=ref.current.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;setTf(`perspective(800px) rotateY(${x*6}deg) rotateX(${-y*6}deg) scale3d(1.015,1.015,1.015)`)};
  return <div ref={ref} onClick={onClick} onMouseMove={move} onMouseLeave={()=>setTf("")} className={cn("relative rounded-2xl border border-white/[0.06] bg-gradient-to-br from-white/[0.04] to-white/[0.01] backdrop-blur-xl shadow-[0_8px_32px_rgba(0,0,0,0.3)] transition-all duration-300",onClick&&"cursor-pointer",className)} style={{transform:tf||undefined}}>{children}</div>;
}
const BV={default:"bg-white/[0.06] text-zinc-400 border-white/[0.06]",success:"bg-emerald-500/10 text-emerald-400 border-emerald-500/15",warning:"bg-amber-500/10 text-amber-400 border-amber-500/15",danger:"bg-red-500/10 text-red-400 border-red-500/15",info:"bg-sky-500/10 text-sky-400 border-sky-500/15",purple:"bg-violet-500/10 text-violet-400 border-violet-500/15",brand:"bg-amber-500/10 text-amber-300 border-amber-500/15"};
function Badge({children,variant="default",className=""}){return <span className={cn("inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1 text-[11px] font-semibold tracking-wide uppercase",BV[variant]||BV.default,className)}>{children}</span>}
const SM={pending:{l:"Pending",v:"warning",i:Clock},confirmed:{l:"Confirmed",v:"info",i:Check},preparing:{l:"In Progress",v:"purple",i:Flame},ready:{l:"Ready",v:"success",i:CheckCircle2},served:{l:"Served",v:"brand",i:UtensilsCrossed},completed:{l:"Completed",v:"success",i:Check},cancelled:{l:"Cancelled",v:"danger",i:X},seated:{l:"Seated",v:"info",i:Armchair}};
function StatusBadge({status}){const s=SM[status]||SM.pending;const I=s.i;return <Badge variant={s.v}><I size={11}/>{s.l}</Badge>}
function KPI({title,value,sub,icon:I,accent="amber"}){const ac=accent==="emerald"?"from-emerald-500/20 to-emerald-500/5 text-emerald-400":accent==="sky"?"from-sky-500/20 to-sky-500/5 text-sky-400":accent==="rose"?"from-rose-500/20 to-rose-500/5 text-rose-400":"from-amber-500/20 to-amber-500/5 text-amber-400";return <Glass hover3d className="group p-6"><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-zinc-500">{title}</p><p className="mt-2 text-3xl font-bold tracking-tight text-white">{value}</p>{sub&&<p className="mt-1.5 text-xs text-zinc-500">{sub}</p>}</div><div className={cn("rounded-xl bg-gradient-to-br p-3",ac)}><I size={22}/></div></div></Glass>}
function Modal({open,onClose,title,children,wide}){if(!open)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}><div className="absolute inset-0 bg-black/70 backdrop-blur-sm"/><div className={cn("relative w-full rounded-2xl border border-white/[0.08] bg-zinc-950/95 shadow-2xl overflow-y-auto max-h-[90vh]",wide?"max-w-2xl":"max-w-md")} onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-white/[0.06] px-6 py-5"><h3 className="text-lg font-semibold text-white">{title}</h3><button onClick={onClose} className="rounded-xl p-2 text-zinc-500 hover:bg-white/[0.06]"><X size={18}/></button></div><div className="p-6">{children}</div></div></div>}
function Input({label,...props}){return <div><label className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.12em] text-zinc-500">{label}</label><input className="w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-amber-500/40 focus:shadow-[0_0_0_3px_rgba(245,158,11,0.1)]" {...props}/></div>}
function Select({label,children,...props}){return <div><label className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.12em] text-zinc-500">{label}</label><select className="w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-sm text-white outline-none focus:border-amber-500/40" {...props}>{children}</select></div>}
function Btn({children,variant="primary",className="",...props}){const v=variant==="primary"?"bg-gradient-to-r from-amber-500 to-amber-600 text-black font-semibold shadow-lg shadow-amber-500/20 hover:shadow-amber-500/30 hover:brightness-110":variant==="danger"?"bg-red-500/15 text-red-400 border border-red-500/20 hover:bg-red-500/25":"border border-white/[0.08] bg-white/[0.03] text-zinc-300 hover:bg-white/[0.06]";return <button className={cn("rounded-xl px-5 py-3 text-sm transition-all duration-200 disabled:opacity-30",v,className)} {...props}>{children}</button>}
function useToast(){const[t,setT]=useState([]);const add=useCallback((m,type="success")=>{const id=uid();setT(p=>[...p,{id,m,type}]);setTimeout(()=>setT(p=>p.filter(x=>x.id!==id)),4000)},[]);return{toasts:t,add}}
function Toasts({toasts}){return <div className="fixed bottom-6 right-6 z-[100] flex flex-col gap-3">{toasts.map(t=><div key={t.id} style={{animation:"toast-in 0.4s cubic-bezier(0.16,1,0.3,1)"}} className={cn("flex items-center gap-3 rounded-2xl border px-5 py-3.5 text-sm font-medium shadow-2xl backdrop-blur-xl",t.type==="success"?"border-emerald-500/20 bg-emerald-500/10 text-emerald-300":t.type==="error"?"border-red-500/20 bg-red-500/10 text-red-300":"border-sky-500/20 bg-sky-500/10 text-sky-300")}>{t.type==="success"?<CheckCircle2 size={18}/>:t.type==="error"?<XCircle size={18}/>:<Info size={18}/>}{t.m}</div>)}</div>}

/* ━━━ Auth ━━━ */
function AuthScreen({onLogin}){const[email,setEmail]=useState("");const[pass,setPass]=useState("");const[loading,setLoading]=useState(false);const[err,setErr]=useState("");const go=()=>{if(!email||!pass){setErr("All fields required");return}setLoading(true);setErr("");setTimeout(()=>{setLoading(false);onLogin(email)},1200)};
  return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#09090b]"><div className="absolute left-1/4 top-0 h-[600px] w-[600px] rounded-full bg-amber-500/[0.03] blur-[150px]"/><div className="absolute right-1/4 bottom-0 h-[500px] w-[500px] rounded-full bg-amber-700/[0.03] blur-[150px]"/><div className="absolute inset-0 opacity-[0.02]" style={{backgroundImage:"linear-gradient(rgba(255,255,255,0.1) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.1) 1px,transparent 1px)",backgroundSize:"60px 60px"}}/>
    <div className="relative z-10 w-full max-w-[420px] px-6" style={{animation:"fade-up 0.8s cubic-bezier(0.16,1,0.3,1)"}}>
      <div className="mb-10 text-center"><div className="mx-auto mb-5 flex h-[72px] w-[72px] items-center justify-center rounded-2xl bg-gradient-to-br from-amber-400 to-amber-600 shadow-[0_20px_60px_rgba(245,158,11,0.25)]"><UtensilsCrossed size={34} className="text-white" strokeWidth={1.5}/></div><h1 className="text-[28px] font-bold tracking-tight text-white" style={{fontFamily:"Georgia,serif"}}>Bella Cucina</h1><p className="mt-1 text-[13px] font-medium tracking-[0.2em] uppercase text-zinc-500">Restaurant Management</p></div>
      <Glass className="p-8"><h2 className="mb-1 text-lg font-semibold text-white">Welcome back</h2><p className="mb-6 text-sm text-zinc-500">Sign in to access your dashboard</p>{err&&<div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-400">{err}</div>}<div className="space-y-5"><Input label="Email" type="email" placeholder="you@restaurant.com" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go()}/><Input label="Password" type="password" placeholder="Enter your password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go()}/></div><Btn className="mt-6 w-full" onClick={go} disabled={loading}>{loading?<span className="inline-flex items-center gap-2"><RefreshCw size={14} className="animate-spin"/>Authenticating...</span>:"Sign In"}</Btn><p className="mt-5 text-center text-[11px] text-zinc-600">Use any credentials to access the demo</p></Glass>
      <div className="mt-8 flex items-center justify-center gap-6 text-[10px] font-medium tracking-[0.15em] uppercase text-zinc-700"><span className="inline-flex items-center gap-1.5"><Shield size={11}/>TLS 1.3</span><span className="inline-flex items-center gap-1.5"><Database size={11}/>RLS</span><span className="inline-flex items-center gap-1.5"><Lock size={11}/>MFA</span></div>
    </div></div>;
}

/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   MAIN APPLICATION
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
export default function RestaurantApp(){
  const[isAuth,setIsAuth]=useState(false);const[user,setUser]=useState(null);const[page,setPage]=useState("dashboard");const[sidebar,setSidebar]=useState(true);const[tick,setTick]=useState(0);const toast=useToast();
  const[orders,setOrders]=useState([]);const[nextNum,setNextNum]=useState(1001);const[menu,setMenu]=useState(seedMenu);const[cats]=useState(seedCats);
  const[tables,setTables]=useState(()=>seedTables.map(t=>({...t,status:"available",orderId:null,guests:0,server:null,seatedAt:null})));
  const[inventory,setInventory]=useState(seedInv);const[staff]=useState(seedStaff);const[customers,setCustomers]=useState(seedCust);const[reservations,setReservations]=useState(seedRes);
  useEffect(()=>{const i=setInterval(()=>setTick(t=>t+1),15000);return()=>clearInterval(i)},[]);
  const active=orders.filter(o=>!["completed","cancelled"].includes(o.status));const done=orders.filter(o=>o.status==="completed");const revenue=done.reduce((s,o)=>s+o.total,0);const occ=tables.filter(t=>t.status==="occupied").length;

  const createOrder=(tableId,items,type,custName)=>{const sub=items.reduce((s,i)=>s+i.price*i.qty,0);const tax=+(sub*0.19).toFixed(2);const o={id:uid(),number:nextNum,tableId,tableNum:tableId?tables.find(t=>t.id===tableId)?.number:"—",type,customerName:custName||"",status:"confirmed",items:items.map(i=>({id:uid(),name:i.name,qty:i.qty,price:i.price,status:"pending",station:i.station,notes:i.notes||""})),subtotal:+sub.toFixed(2),tax,tip:0,total:+(sub+tax).toFixed(2),guests:1,waiter:user||"Staff",createdAt:new Date().toISOString()};setOrders(p=>[o,...p]);setNextNum(n=>n+1);if(tableId)setTables(p=>p.map(t=>t.id===tableId?{...t,status:"occupied",orderId:o.id,guests:o.guests,server:o.waiter,seatedAt:new Date().toISOString()}:t));setInventory(p=>p.map(inv=>({...inv,qty:Math.max(0,+(inv.qty-items.reduce((s,i)=>s+i.qty*0.05,0)).toFixed(3))})));toast.add(`Order #${nextNum} confirmed`)};
  const advanceOrder=(id,to)=>{setOrders(p=>p.map(o=>o.id===id?{...o,status:to,completedAt:to==="completed"?new Date().toISOString():o.completedAt}:o));if(to==="completed"||to==="cancelled"){const o=orders.find(x=>x.id===id);if(o?.tableId){setTables(p=>p.map(t=>t.id===o.tableId?{...t,status:"cleaning",orderId:null,guests:0,server:null}:t));setTimeout(()=>setTables(p=>p.map(t=>t.id===o.tableId&&t.status==="cleaning"?{...t,status:"available"}:t)),5000)}}toast.add(`Order → ${to}`)};
  const bumpItem=(oid,iid)=>{setOrders(p=>p.map(o=>{if(o.id!==oid)return o;const items=o.items.map(i=>i.id===iid?{...i,status:i.status==="pending"?"preparing":i.status==="preparing"?"ready":"served"}:i);const allR=items.every(i=>["ready","served"].includes(i.status));const allS=items.every(i=>i.status==="served");return{...o,items,status:allS?"served":allR?"ready":items.some(i=>i.status==="preparing")?"preparing":o.status}}))};
  const bumpAll=(oid)=>{setOrders(p=>p.map(o=>{if(o.id!==oid)return o;const items=o.items.map(i=>({...i,status:i.status==="pending"?"preparing":i.status==="preparing"?"ready":"served"}));return{...o,items,status:items.every(i=>["ready","served"].includes(i.status))?"ready":"preparing"}}));toast.add("All items advanced")};
  const seatRes=(rid)=>{const r=reservations.find(x=>x.id===rid);if(!r)return;setReservations(p=>p.map(x=>x.id===rid?{...x,status:"seated"}:x));if(r.tableId)setTables(p=>p.map(t=>t.id===r.tableId?{...t,status:"occupied",guests:r.size,server:"Host",seatedAt:new Date().toISOString()}:t));toast.add(`${r.name} seated`)};
  const nxt={confirmed:"preparing",preparing:"ready",ready:"served",served:"completed"};

  if(!isAuth)return<><AuthScreen onLogin={e=>{setIsAuth(true);setUser(e.split("@")[0])}}/><Styles/></>;

  /* ── Pages ── */
  const Dashboard=()=><div className="space-y-8 anim-stagger">
    <div className="flex items-center justify-between"><div><h1 className="text-[26px] font-bold tracking-tight text-white">Overview</h1><p className="mt-0.5 text-sm text-zinc-500">Real-time operations — {new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</p></div><Badge variant="success"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"/><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400"/></span>Live</Badge></div>
    <div className="grid grid-cols-2 gap-5 lg:grid-cols-4"><KPI title="Revenue" value={fmt(revenue)} sub={done.length?`${done.length} completed`:null} icon={DollarSign}/><KPI title="Active" value={active.length} sub="In pipeline" icon={ShoppingBag} accent="sky"/><KPI title="Occupancy" value={`${occ}/${tables.length}`} sub={`${Math.round(occ/tables.length*100)}%`} icon={Armchair} accent="emerald"/><KPI title="Avg Check" value={done.length?fmt(revenue/done.length):"—"} icon={Receipt} accent="rose"/></div>
    <div className="grid gap-6 lg:grid-cols-5">
      <Glass className="lg:col-span-3 p-6"><h2 className="mb-5 text-[13px] font-semibold uppercase tracking-[0.12em] text-zinc-500">Revenue Trend</h2><ResponsiveContainer width="100%" height={240}><AreaChart data={[{d:"Mon",v:2840},{d:"Tue",v:2120},{d:"Wed",v:3150},{d:"Thu",v:3680},{d:"Fri",v:5240},{d:"Sat",v:6120},{d:"Sun",v:revenue||4580}]}><defs><linearGradient id="rg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f59e0b" stopOpacity={0.25}/><stop offset="100%" stopColor="#f59e0b" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)"/><XAxis dataKey="d" stroke="#3f3f46" fontSize={11} tickLine={false}/><YAxis stroke="#3f3f46" fontSize={11} tickLine={false} tickFormatter={v=>`€${v}`}/><Tooltip contentStyle={{background:"rgba(9,9,11,0.95)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"12px",fontSize:"12px",boxShadow:"0 20px 60px rgba(0,0,0,0.5)"}}/><Area type="monotone" dataKey="v" stroke="#f59e0b" fill="url(#rg)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Glass>
      <Glass className="lg:col-span-2 p-6"><h2 className="mb-4 text-[13px] font-semibold uppercase tracking-[0.12em] text-zinc-500">Active Pipeline</h2><div className="space-y-2.5 max-h-[260px] overflow-y-auto pr-1">{active.length===0?<p className="py-10 text-center text-sm text-zinc-600">No active orders</p>:active.slice(0,8).map(o=><div key={o.id} onClick={()=>setPage("orders")} className="flex items-center justify-between rounded-xl border border-white/[0.04] bg-white/[0.02] p-3.5 hover:bg-white/[0.04] cursor-pointer transition-all"><div><span className="text-sm font-bold text-white">#{o.number}</span>{o.tableNum!=="—"&&<span className="ml-2 text-xs text-zinc-600">T{o.tableNum}</span>}<p className="text-xs text-zinc-600 mt-0.5">{o.items.length} items · {fmt(o.total)}</p></div><div className="text-right"><StatusBadge status={o.status}/><p className={cn("mt-1 text-[11px] font-mono",urgClass(o.createdAt))}>{fmtTime(o.createdAt)}</p></div></div>)}</div></Glass>
    </div>
    {inventory.filter(i=>i.qty<=i.threshold).length>0&&<Glass className="border-red-500/10 p-5"><div className="flex items-center gap-3 mb-3"><div className="rounded-lg bg-red-500/10 p-2"><AlertTriangle size={16} className="text-red-400"/></div><span className="text-sm font-semibold text-red-300">Low Stock</span></div><div className="flex flex-wrap gap-2">{inventory.filter(i=>i.qty<=i.threshold).map(i=><Badge key={i.id} variant="danger">{i.name} — {i.qty} {i.unit}</Badge>)}</div></Glass>}
    <Glass className="p-6"><h2 className="mb-4 text-[13px] font-semibold uppercase tracking-[0.12em] text-zinc-500">Reservations</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{reservations.filter(r=>r.status==="confirmed").length===0?<p className="col-span-full py-6 text-center text-sm text-zinc-600">No pending</p>:reservations.filter(r=>r.status==="confirmed").slice(0,3).map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border border-white/[0.04] bg-white/[0.02] p-4"><div className="flex items-center gap-4"><div className="flex h-12 w-12 flex-col items-center justify-center rounded-xl bg-amber-500/10 border border-amber-500/10"><span className="text-base font-bold text-amber-400">{r.time.split(":")[0]}</span><span className="text-[10px] text-amber-500/60">:{r.time.split(":")[1]}</span></div><div><p className="text-sm font-semibold text-white">{r.name}</p><p className="text-xs text-zinc-500">{r.size} guests · T{tables.find(t=>t.id===r.tableId)?.number}</p></div></div><Btn className="text-xs py-2 px-4" onClick={()=>seatRes(r.id)}>Seat</Btn></div>)}</div></Glass>
  </div>;

  const POS=()=>{const[cat,setCat]=useState("c1");const[cart,setCart]=useState([]);const[tbl,setTbl]=useState("");const[otype,setOtype]=useState("dine_in");const[cname,setCname]=useState("");const add=i=>setCart(p=>{const e=p.find(c=>c.id===i.id);return e?p.map(c=>c.id===i.id?{...c,qty:c.qty+1}:c):[...p,{...i,qty:1,notes:""}]});const sub=cart.reduce((s,c)=>s+c.price*c.qty,0);const tax=+(sub*0.19).toFixed(2);const total=+(sub+tax).toFixed(2);const avail=menu.filter(m=>m.catId===cat&&m.available);const free=tables.filter(t=>t.status==="available");const send=()=>{if(!cart.length)return;if(otype==="dine_in"&&!tbl){toast.add("Select table","error");return}createOrder(otype==="dine_in"?tbl:null,cart,otype,cname);setCart([]);setTbl("");setCname("")};
    return <div className="flex h-[calc(100vh-7.5rem)] gap-5"><div className="flex flex-1 flex-col min-w-0"><div className="mb-4 flex gap-2 overflow-x-auto pb-1 shrink-0">{cats.map(c=>{const CI=CAT_ICONS[c.id]||Circle;return <button key={c.id} onClick={()=>setCat(c.id)} className={cn("shrink-0 flex items-center gap-2.5 rounded-xl px-5 py-3 text-sm font-semibold transition-all",cat===c.id?"bg-gradient-to-r from-amber-500 to-amber-600 text-black shadow-lg shadow-amber-500/20":"bg-white/[0.03] border border-white/[0.06] text-zinc-400 hover:bg-white/[0.06] hover:text-white")}><CI size={16}/>{c.name}</button>})}</div><div className="grid flex-1 gap-3 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 content-start pr-1">{avail.map(i=><Glass key={i.id} hover3d onClick={()=>{add(i);toast.add(`${i.name} added`,"info")}} className="group p-5"><div className="flex items-start justify-between"><h3 className="text-sm font-semibold text-white group-hover:text-amber-400 transition-colors">{i.name}</h3></div><p className="mt-1.5 text-xs text-zinc-600">{i.station} · {i.prepTime}m</p><p className="mt-3 text-xl font-bold text-white">{fmt(i.price)}</p></Glass>)}{avail.length===0&&<p className="col-span-full text-center text-sm text-zinc-600 py-16">No items</p>}</div></div>
      <Glass className="flex w-[340px] shrink-0 flex-col"><div className="border-b border-white/[0.06] p-5 space-y-4"><div className="flex gap-2">{["dine_in","takeout"].map(t=><button key={t} onClick={()=>setOtype(t)} className={cn("flex-1 rounded-xl py-2.5 text-xs font-semibold uppercase tracking-wider transition-all",otype===t?"bg-amber-500 text-black":"bg-white/[0.03] border border-white/[0.06] text-zinc-400")}>{t.replace("_"," ")}</button>)}</div>{otype==="dine_in"?<Select label="Assign Table" value={tbl} onChange={e=>setTbl(e.target.value)}><option value="">Select...</option>{free.map(t=><option key={t.id} value={t.id}>Table {t.number} — {t.capacity} seats</option>)}</Select>:<Input label="Guest" placeholder="Name" value={cname} onChange={e=>setCname(e.target.value)}/>}</div>
      <div className="flex-1 overflow-y-auto p-5 space-y-2.5">{cart.length===0?<div className="flex flex-col items-center py-14"><ShoppingBag size={36} className="text-zinc-700 mb-3" strokeWidth={1.5}/><p className="text-sm text-zinc-600">Select items to begin</p></div>:cart.map(i=><div key={i.id} className="rounded-xl border border-white/[0.04] bg-white/[0.02] p-3.5"><div className="flex justify-between mb-2"><p className="text-sm font-medium text-white truncate pr-2">{i.name}</p><button onClick={()=>setCart(p=>p.filter(c=>c.id!==i.id))} className="text-zinc-600 hover:text-red-400"><X size={14}/></button></div><input className="w-full rounded-lg bg-white/[0.03] border border-white/[0.04] px-3 py-1.5 text-[11px] text-zinc-400 outline-none mb-2 placeholder:text-zinc-700" placeholder="Notes..." value={i.notes} onChange={e=>setCart(p=>p.map(c=>c.id===i.id?{...c,notes:e.target.value}:c))}/><div className="flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={()=>setCart(p=>p.map(c=>c.id===i.id?{...c,qty:Math.max(1,c.qty-1)}:c))} className="rounded-lg bg-white/[0.06] px-2.5 py-1 text-xs text-zinc-300">−</button><span className="w-6 text-center text-sm font-bold text-white">{i.qty}</span><button onClick={()=>setCart(p=>p.map(c=>c.id===i.id?{...c,qty:c.qty+1}:c))} className="rounded-lg bg-white/[0.06] px-2.5 py-1 text-xs text-zinc-300">+</button></div><span className="text-sm font-bold text-white">{fmt(i.price*i.qty)}</span></div></div>)}</div>
      <div className="border-t border-white/[0.06] p-5 space-y-4"><div className="space-y-2"><div className="flex justify-between text-sm text-zinc-500"><span>Subtotal</span><span className="text-zinc-300">{fmt(sub)}</span></div><div className="flex justify-between text-sm text-zinc-500"><span>Tax 19%</span><span className="text-zinc-300">{fmt(tax)}</span></div><div className="flex justify-between text-lg font-bold text-white border-t border-white/[0.06] pt-3"><span>Total</span><span>{fmt(total)}</span></div></div><Btn className="w-full" onClick={send} disabled={!cart.length}>Send to Kitchen</Btn></div></Glass></div>;
  };

  const Kitchen=()=>{const[st,setSt]=useState("all");const ko=orders.filter(o=>["confirmed","preparing","ready"].includes(o.status)).map(o=>({...o,items:st==="all"?o.items.filter(i=>i.status!=="served"):o.items.filter(i=>i.station===st&&i.status!=="served")})).filter(o=>o.items.length>0);
    return <div className="space-y-5"><div className="flex items-center justify-between"><h1 className="text-[26px] font-bold tracking-tight text-white">Kitchen</h1><Badge variant="success"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"/><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400"/></span>Live</Badge></div><div className="flex gap-2">{["all","grill","pasta","pizza","salad","bar"].map(s=><button key={s} onClick={()=>setSt(s)} className={cn("rounded-xl px-5 py-2.5 text-sm font-semibold uppercase tracking-wider transition-all",st===s?"bg-amber-500 text-black shadow-lg shadow-amber-500/20":"bg-white/[0.03] border border-white/[0.06] text-zinc-400 hover:text-white")}>{s}</button>)}</div>
      {ko.length===0?<div className="flex flex-col items-center py-24"><ChefHat size={48} className="text-zinc-700 mb-3" strokeWidth={1.5}/><p className="text-xl font-semibold text-zinc-400">All clear</p><p className="text-sm text-zinc-600 mt-1">Orders appear here in real-time</p></div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{ko.map(o=>{const m=minsAgo(o.createdAt);return <Glass key={o.id} className={cn("p-5",m>20?"border-red-500/20":m>12?"border-amber-500/20":"")}>
        <div className="flex items-center justify-between mb-3"><span className="text-xl font-black text-white">#{o.number}</span><div className="text-right"><Badge>{o.tableNum!=="—"?`T${o.tableNum}`:o.type}</Badge><p className={cn("text-xs font-mono font-bold mt-1",m>20?"text-red-400":m>12?"text-amber-400":"text-emerald-400")}>{m}m</p></div></div><p className="text-xs text-zinc-600 mb-3">{o.waiter}</p>
        <div className="space-y-2">{o.items.map(i=><div key={i.id} className={cn("flex items-center justify-between rounded-xl px-3.5 py-2.5",i.status==="ready"?"bg-emerald-500/10 border border-emerald-500/10":i.status==="preparing"?"bg-sky-500/5 border border-sky-500/10":"bg-white/[0.02] border border-white/[0.04]")}><div className="flex-1 min-w-0"><span className={cn("text-sm font-medium",i.status==="ready"?"text-emerald-400 line-through":"text-white")}>{i.qty}× {i.name}</span>{i.notes&&<p className="text-[11px] font-semibold text-red-400 mt-0.5">{i.notes}</p>}</div><button onClick={()=>{bumpItem(o.id,i.id);toast.add("Bumped","info")}} className={cn("rounded-lg px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider transition-all",i.status==="ready"?"bg-emerald-500/20 text-emerald-400":"bg-white/[0.06] text-zinc-300 hover:bg-amber-500 hover:text-black")}>{i.status==="pending"?"Fire":i.status==="preparing"?"Ready":"Done"}</button></div>)}</div>
        <button onClick={()=>bumpAll(o.id)} className="mt-4 w-full rounded-xl bg-gradient-to-r from-emerald-500 to-emerald-600 py-2.5 text-xs font-bold uppercase tracking-wider text-white shadow-lg shadow-emerald-500/20 hover:brightness-110 transition-all">Advance All</button></Glass>})}</div>}</div>;
  };

  const Orders=()=>{const[f,setF]=useState("all");const fl=f==="all"?orders:orders.filter(o=>o.status===f);return <div className="space-y-6 anim-stagger"><div className="flex items-center justify-between"><div><h1 className="text-[26px] font-bold tracking-tight text-white">Orders</h1><p className="text-sm text-zinc-500">{orders.length} total</p></div><Btn onClick={()=>setPage("pos")}><Plus size={16} className="mr-1.5 inline"/>New</Btn></div><div className="flex flex-wrap gap-2">{["all","confirmed","preparing","ready","served","completed","cancelled"].map(s=><button key={s} onClick={()=>setF(s)} className={cn("rounded-xl px-4 py-2 text-xs font-semibold uppercase tracking-wider transition-all",f===s?"bg-amber-500/10 text-amber-400 border border-amber-500/15":"border border-white/[0.06] text-zinc-500 hover:text-white")}>{s==="all"?`All (${orders.length})`:s}</button>)}</div>{fl.length===0?<Glass className="py-16 text-center"><ShoppingBag size={40} className="mx-auto text-zinc-700 mb-4" strokeWidth={1.5}/><p className="text-zinc-500">No orders yet</p></Glass>:<Glass className="overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-white/[0.06] bg-white/[0.02]">{["Order","Table","Items","Status","Total","Elapsed","Actions"].map(h=><th key={h} className={cn("px-5 py-4 text-[11px] font-semibold uppercase tracking-[0.12em] text-zinc-500",h==="Actions"?"text-right":"text-left")}>{h}</th>)}</tr></thead><tbody>{fl.map(o=><tr key={o.id} className="border-b border-white/[0.03] hover:bg-white/[0.02] transition-colors"><td className="px-5 py-4 font-bold text-white">#{o.number}{o.type!=="dine_in"&&<Badge variant="info" className="ml-2 text-[9px]">{o.type}</Badge>}</td><td className="px-5 py-4 text-zinc-400">{o.tableNum}</td><td className="px-5 py-4 text-zinc-400">{o.items.length}</td><td className="px-5 py-4"><StatusBadge status={o.status}/></td><td className="px-5 py-4 font-semibold text-white">{fmt(o.total)}</td><td className={cn("px-5 py-4 font-mono text-xs",urgClass(o.createdAt))}>{fmtTime(o.createdAt)}</td><td className="px-5 py-4 text-right"><div className="flex gap-2 justify-end">{nxt[o.status]&&<button onClick={()=>advanceOrder(o.id,nxt[o.status])} className="rounded-lg bg-amber-500 px-3.5 py-1.5 text-xs font-semibold text-black hover:bg-amber-400">→ {nxt[o.status]}</button>}{!["completed","cancelled"].includes(o.status)&&<button onClick={()=>advanceOrder(o.id,"cancelled")} className="rounded-lg bg-white/[0.04] p-1.5 text-red-400 hover:bg-red-500/15"><X size={13}/></button>}</div></td></tr>)}</tbody></table></Glass>}</div>};

  const Menu=()=>{const[cat,setCat]=useState("all");const[modal,setModal]=useState(null);const items=cat==="all"?menu:menu.filter(m=>m.catId===cat);const save=i=>{if(i.id){setMenu(p=>p.map(m=>m.id===i.id?i:m));toast.add("Updated")}else{setMenu(p=>[{...i,id:uid()},...p]);toast.add("Created")}setModal(null)};
    return <div className="space-y-6 anim-stagger"><div className="flex items-center justify-between"><h1 className="text-[26px] font-bold tracking-tight text-white">Menu</h1><Btn onClick={()=>setModal({id:null,name:"",catId:"c1",price:0,cost:0,available:true,prepTime:15,calories:0,allergens:[],station:"salad"})}><Plus size={16} className="mr-1.5 inline"/>Add</Btn></div><div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCat("all")} className={cn("shrink-0 rounded-xl px-4 py-2.5 text-xs font-semibold uppercase tracking-wider",cat==="all"?"bg-amber-500/10 text-amber-400 border border-amber-500/15":"border border-white/[0.06] text-zinc-500")}>All</button>{cats.map(c=>{const CI=CAT_ICONS[c.id];return <button key={c.id} onClick={()=>setCat(c.id)} className={cn("shrink-0 flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold uppercase tracking-wider",cat===c.id?"bg-amber-500/10 text-amber-400 border border-amber-500/15":"border border-white/[0.06] text-zinc-500 hover:text-white")}><CI size={14}/>{c.name}</button>})}</div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(i=>{const CI=CAT_ICONS[i.catId]||Circle;const mg=i.cost?Math.round((1-i.cost/i.price)*100):null;return <Glass key={i.id} hover3d className={cn("group p-5",!i.available&&"opacity-40")}><div className="flex items-center justify-between mb-3"><Badge variant={i.available?"success":"danger"}>{i.available?"Active":"Unavailable"}</Badge><div className="rounded-lg p-2 bg-white/[0.03]" style={{color:CAT_COLORS[i.catId]}}><CI size={16}/></div></div><h3 className="text-sm font-semibold text-white">{i.name}</h3><div className="mt-2 flex items-baseline gap-3"><span className="text-2xl font-bold text-white">{fmt(i.price)}</span>{i.cost>0&&<span className="text-xs text-zinc-600">Cost {fmt(i.cost)}</span>}</div>{mg!==null&&<div className="mt-3 flex items-center gap-2"><div className="h-1 flex-1 rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-emerald-500/70" style={{width:`${mg}%`}}/></div><span className="text-[11px] text-zinc-500">{mg}%</span></div>}<div className="mt-3 flex flex-wrap gap-1.5"><Badge><Clock size={10}/>{i.prepTime}m</Badge><Badge>{i.station}</Badge>{i.allergens?.map(a=><Badge key={a} variant="warning">{a}</Badge>)}</div><div className="mt-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={()=>setModal({...i})} className="flex-1 rounded-lg bg-white/[0.06] py-2 text-xs text-zinc-300 hover:bg-white/[0.1]"><Edit size={12} className="inline mr-1"/>Edit</button><button onClick={()=>setMenu(p=>p.map(m=>m.id===i.id?{...m,available:!m.available}:m))} className="rounded-lg bg-white/[0.06] px-3 py-2 text-xs text-zinc-300 hover:bg-white/[0.1]">{i.available?<EyeOff size={12}/>:<Eye size={12}/>}</button><button onClick={()=>{setMenu(p=>p.filter(m=>m.id!==i.id));toast.add("Removed","info")}} className="rounded-lg bg-white/[0.06] px-3 py-2 text-xs text-red-400 hover:bg-red-500/15"><Trash2 size={12}/></button></div></Glass>})}</div>
      <Modal open={!!modal} onClose={()=>setModal(null)} title={modal?.id?"Edit Item":"New Item"} wide>{modal&&<MenuForm item={modal} cats={cats} onSave={save} onCancel={()=>setModal(null)}/>}</Modal></div>;
  };

  const Tables=()=>{const[sec,setSec]=useState("all");const shown=sec==="all"?tables:tables.filter(t=>t.section===sec);const secs=[...new Set(tables.map(t=>t.section))];const dot={available:"bg-emerald-500",occupied:"bg-red-500",reserved:"bg-amber-500",cleaning:"bg-zinc-500"};const bg={available:"border-emerald-500/15 from-emerald-500/5",occupied:"border-red-500/15 from-red-500/5",reserved:"border-amber-500/15 from-amber-500/5",cleaning:"border-white/[0.04] from-white/[0.02]"};
    return <div className="space-y-6 anim-stagger"><h1 className="text-[26px] font-bold tracking-tight text-white">Floor Plan</h1><div className="flex flex-wrap items-center gap-3">{Object.keys(dot).map(s=><span key={s} className="inline-flex items-center gap-2 text-xs text-zinc-500 capitalize"><span className={cn("h-2 w-2 rounded-full",dot[s])}/>{s}</span>)}<div className="mx-2 h-4 w-px bg-white/[0.06]"/>{["all",...secs].map(s=><button key={s} onClick={()=>setSec(s)} className={cn("rounded-xl px-3.5 py-1.5 text-xs font-semibold uppercase tracking-wider",sec===s?"bg-amber-500/10 text-amber-400":"text-zinc-600 hover:text-white")}>{s}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">{shown.map(t=>{const o=orders.find(x=>x.id===t.orderId);return <Glass key={t.id} hover3d className={cn("p-5 border bg-gradient-to-br to-transparent",bg[t.status]||bg.available)}><div className="flex items-center justify-between"><span className="text-xl font-black text-white">{t.number}</span><span className={cn("h-2.5 w-2.5 rounded-full shadow-lg",dot[t.status])}/></div><p className="text-xs text-zinc-500 mt-2"><Users size={11} className="inline mr-1"/>{t.status==="occupied"?`${t.guests}/${t.capacity}`:t.capacity} · {t.section}</p>{t.status==="occupied"&&<div className="mt-2.5 pt-2.5 border-t border-white/[0.04]"><p className="text-xs text-zinc-400">{t.server}</p>{t.seatedAt&&<p className={cn("text-[11px] font-mono",urgClass(t.seatedAt))}>{fmtTime(t.seatedAt)}</p>}{o&&<p className="text-xs text-zinc-500 mt-0.5">#{o.number} · {fmt(o.total)}</p>}</div>}{t.status==="available"&&<button onClick={()=>setPage("pos")} className="mt-3 w-full rounded-lg bg-white/[0.06] py-2 text-xs text-zinc-400 hover:bg-amber-500 hover:text-black transition-all">Seat</button>}</Glass>})}</div></div>;
  };

  const Inventory=()=>{const[eid,setEid]=useState(null);const[eq,setEq]=useState("");return <div className="space-y-6 anim-stagger"><h1 className="text-[26px] font-bold tracking-tight text-white">Inventory</h1><Glass className="overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-white/[0.06] bg-white/[0.02]">{["Item","Category","Stock","Status","Cost","Supplier",""].map(h=><th key={h} className={cn("px-5 py-4 text-[11px] font-semibold uppercase tracking-[0.12em] text-zinc-500",h===""?"text-right":"text-left")}>{h}</th>)}</tr></thead><tbody>{inventory.map(i=>{const low=i.qty<=i.threshold;const pct=Math.min(100,(i.qty/i.par)*100);return <tr key={i.id} className={cn("border-b border-white/[0.03] hover:bg-white/[0.02]",low&&"bg-red-500/[0.03]")}><td className="px-5 py-4 font-medium text-white">{i.name}</td><td className="px-5 py-4"><Badge>{i.category}</Badge></td><td className="px-5 py-4">{eid===i.id?<div className="flex items-center gap-2"><input className="w-20 rounded-lg bg-white/[0.06] border border-white/[0.1] px-3 py-1.5 text-sm text-white outline-none" value={eq} onChange={e=>setEq(e.target.value)} autoFocus/><button onClick={()=>{setInventory(p=>p.map(x=>x.id===i.id?{...x,qty:+eq}:x));setEid(null);toast.add("Updated")}} className="text-emerald-400"><Check size={14}/></button><button onClick={()=>setEid(null)} className="text-zinc-500"><X size={14}/></button></div>:<div className="flex items-center gap-3"><span className={cn("font-semibold",low?"text-red-400":"text-white")}>{i.qty} {i.unit}</span><div className="h-1.5 w-20 rounded-full bg-white/[0.06]"><div className={cn("h-full rounded-full",low?"bg-red-500":pct>60?"bg-emerald-500":"bg-amber-500")} style={{width:`${pct}%`}}/></div></div>}</td><td className="px-5 py-4">{low?<Badge variant="danger"><AlertTriangle size={10}/>Low</Badge>:<Badge variant="success"><Check size={10}/>OK</Badge>}</td><td className="px-5 py-4 text-zinc-400">{fmt(i.cost)}/{i.unit}</td><td className="px-5 py-4 text-zinc-400">{i.supplier}</td><td className="px-5 py-4 text-right"><button onClick={()=>{setEid(i.id);setEq(String(i.qty))}} className="rounded-lg bg-white/[0.06] px-3.5 py-1.5 text-xs text-zinc-300 hover:bg-white/[0.1]"><Edit size={12} className="inline mr-1"/>Adjust</button></td></tr>})}</tbody></table></Glass></div>};

  const Reservations=()=>{const[modal,setModal]=useState(false);const[form,setForm]=useState({name:"",phone:"",size:2,time:"19:00",tableId:"",notes:""});const addR=()=>{if(!form.name.trim()){toast.add("Name required","error");return}setReservations(p=>[{id:uid(),...form,date:"Today",status:"confirmed"},...p]);if(form.tableId)setTables(p=>p.map(t=>t.id===form.tableId?{...t,status:"reserved"}:t));toast.add(`${form.name} confirmed`);setModal(false);setForm({name:"",phone:"",size:2,time:"19:00",tableId:"",notes:""})};
    return <div className="space-y-6 anim-stagger"><div className="flex items-center justify-between"><h1 className="text-[26px] font-bold tracking-tight text-white">Reservations</h1><Btn onClick={()=>setModal(true)}><Plus size={16} className="mr-1.5 inline"/>New</Btn></div><div className="space-y-3">{reservations.map(r=><Glass key={r.id} className="flex items-center justify-between p-5"><div className="flex items-center gap-5"><div className="flex h-14 w-14 flex-col items-center justify-center rounded-xl bg-gradient-to-br from-amber-500/15 to-amber-500/5 border border-amber-500/10"><span className="text-lg font-bold text-amber-400">{r.time.split(":")[0]}</span><span className="text-[10px] text-amber-500/50">:{r.time.split(":")[1]}</span></div><div><p className="text-sm font-semibold text-white">{r.name}</p><p className="text-xs text-zinc-500 mt-0.5"><Users size={11} className="inline mr-1"/>{r.size}{r.tableId&&<> · T{tables.find(t=>t.id===r.tableId)?.number}</>}{r.phone&&<> · {r.phone}</>}</p>{r.notes&&<p className="text-[11px] text-zinc-600 italic mt-0.5">{r.notes}</p>}</div></div><div className="flex items-center gap-3"><StatusBadge status={r.status}/>{r.status==="confirmed"&&<><Btn className="text-xs py-2 px-4" onClick={()=>seatRes(r.id)}>Seat</Btn><button onClick={()=>{setReservations(p=>p.map(x=>x.id===r.id?{...x,status:"cancelled"}:x));if(r.tableId)setTables(p=>p.map(t=>t.id===r.tableId&&t.status==="reserved"?{...t,status:"available"}:t));toast.add("Cancelled","info")}} className="rounded-lg bg-white/[0.04] p-2 text-red-400 hover:bg-red-500/15"><X size={14}/></button></>}</div></Glass>)}</div><Modal open={modal} onClose={()=>setModal(false)} title="New Reservation"><div className="space-y-5"><Input label="Guest Name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><Input label="Phone" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/><div className="grid grid-cols-2 gap-4"><Input label="Party Size" type="number" value={form.size} onChange={e=>setForm(f=>({...f,size:+e.target.value}))}/><Input label="Time" type="time" value={form.time} onChange={e=>setForm(f=>({...f,time:e.target.value}))}/></div><Select label="Table" value={form.tableId} onChange={e=>setForm(f=>({...f,tableId:e.target.value}))}><option value="">Auto</option>{tables.filter(t=>t.status==="available").map(t=><option key={t.id} value={t.id}>Table {t.number} — {t.capacity} seats</option>)}</Select><Input label="Notes" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/><Btn className="w-full" onClick={addR}>Confirm</Btn></div></Modal></div>};

  const Staff=()=>{const rc={Owner:"brand",Manager:"info","Head Chef":"purple",Server:"success",Cashier:"warning",Host:"default"};return <div className="space-y-6 anim-stagger"><h1 className="text-[26px] font-bold tracking-tight text-white">Team</h1><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{staff.map(s=><Glass key={s.id} hover3d className={cn("p-6",!s.active&&"opacity-40")}><div className="flex items-center gap-4 mb-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-amber-500/15 to-amber-500/5 text-sm font-bold text-amber-400">{s.initials}</div><div><p className="font-semibold text-white">{s.name}</p><Badge variant={rc[s.role]}>{s.role}</Badge></div></div><div className="space-y-2 text-xs text-zinc-500"><p><Mail size={12} className="inline mr-2"/>{s.email}</p>{s.rate>0&&<p><DollarSign size={12} className="inline mr-2"/>{fmt(s.rate)}/hr</p>}<p>{s.active?<Wifi size={12} className="inline mr-2 text-emerald-400"/>:<WifiOff size={12} className="inline mr-2"/>}{s.active?"On Shift":"Off Duty"}</p></div></Glass>)}</div></div>};

  const Analytics=()=>{const is={};done.forEach(o=>o.items.forEach(i=>{if(!is[i.name])is[i.name]={name:i.name,orders:0,revenue:0};is[i.name].orders+=i.qty;is[i.name].revenue+=i.price*i.qty}));const top=Object.values(is).sort((a,b)=>b.revenue-a.revenue).slice(0,6);const td=[{name:"Dine-in",value:orders.filter(o=>o.type==="dine_in").length||1,color:"#f59e0b"},{name:"Takeout",value:orders.filter(o=>o.type==="takeout").length||1,color:"#3b82f6"}];
    return <div className="space-y-6 anim-stagger"><h1 className="text-[26px] font-bold tracking-tight text-white">Analytics</h1><div className="grid grid-cols-2 gap-5 lg:grid-cols-4"><KPI title="Revenue" value={fmt(revenue)} icon={DollarSign}/><KPI title="Orders" value={orders.length} icon={ShoppingBag} accent="sky"/><KPI title="Avg Check" value={done.length?fmt(revenue/done.length):"—"} icon={Target} accent="emerald"/><KPI title="Completion" value={orders.length?Math.round(done.length/orders.length*100)+"%":"—"} icon={CheckCircle2} accent="rose"/></div><div className="grid gap-6 lg:grid-cols-2"><Glass className="p-6"><h2 className="mb-5 text-[13px] font-semibold uppercase tracking-[0.12em] text-zinc-500">Top Items</h2>{top.length?<ResponsiveContainer width="100%" height={220}><ReBarChart data={top} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)"/><XAxis type="number" stroke="#3f3f46" fontSize={11} tickFormatter={v=>`€${v}`}/><YAxis type="category" dataKey="name" stroke="#3f3f46" fontSize={11} width={120}/><Tooltip contentStyle={{background:"rgba(9,9,11,0.95)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"12px"}}/><Bar dataKey="revenue" fill="#f59e0b" radius={[0,6,6,0]}/></ReBarChart></ResponsiveContainer>:<p className="text-sm text-zinc-600 text-center py-16">Complete orders first</p>}</Glass><Glass className="p-6"><h2 className="mb-5 text-[13px] font-semibold uppercase tracking-[0.12em] text-zinc-500">Distribution</h2><div className="flex items-center gap-8"><ResponsiveContainer width="50%" height={180}><RePieChart><Pie data={td} cx="50%" cy="50%" innerRadius={45} outerRadius={75} dataKey="value" stroke="none">{td.map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie></RePieChart></ResponsiveContainer><div className="space-y-3">{td.map(d=><div key={d.name} className="flex items-center gap-3"><div className="h-3 w-3 rounded" style={{background:d.color}}/><span className="text-xs text-zinc-400">{d.name}</span><span className="text-xs font-bold text-white">{d.value}</span></div>)}</div></div></Glass></div></div>};

  const Customers=()=>{const[modal,setModal]=useState(false);const[form,setForm]=useState({name:"",email:"",phone:"",notes:""});const add=()=>{if(!form.name.trim()){toast.add("Name required","error");return}setCustomers(p=>[{id:uid(),...form,visits:0,spent:0,points:0,tags:[]},...p]);toast.add(`${form.name} added`);setModal(false);setForm({name:"",email:"",phone:"",notes:""})};
    return <div className="space-y-6 anim-stagger"><div className="flex items-center justify-between"><h1 className="text-[26px] font-bold tracking-tight text-white">Guests</h1><Btn onClick={()=>setModal(true)}><Plus size={16} className="mr-1.5 inline"/>Add</Btn></div><div className="space-y-3">{customers.map(c=><Glass key={c.id} className="flex items-center justify-between p-5"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-amber-500/15 to-amber-500/5 text-sm font-bold text-amber-400">{c.name.split(" ").map(w=>w[0]).join("").slice(0,2)}</div><div><div className="flex items-center gap-2"><p className="font-semibold text-white">{c.name}</p>{c.tags?.map(t=><Badge key={t} variant={t==="VIP"?"brand":"default"}>{t}</Badge>)}</div><p className="text-xs text-zinc-500 mt-0.5">{[c.email,c.phone].filter(Boolean).join(" · ")}</p>{c.notes&&<p className="text-[11px] text-zinc-600 italic mt-0.5">{c.notes}</p>}</div></div><div className="text-right"><p className="text-sm font-bold text-white">{fmt(c.spent)}</p><p className="text-xs text-zinc-500">{c.visits} visits</p>{c.points>0&&<Badge variant="brand" className="mt-1"><Star size={10}/>{c.points}</Badge>}</div></Glass>)}</div><Modal open={modal} onClose={()=>setModal(false)} title="Add Guest"><div className="space-y-5"><Input label="Name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><Input label="Email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/><Input label="Phone" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/><Input label="Notes" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/><Btn className="w-full" onClick={add}>Add Guest</Btn></div></Modal></div>};

  const SettingsPage=()=><div className="space-y-6 anim-stagger"><h1 className="text-[26px] font-bold tracking-tight text-white">Settings</h1><div className="grid gap-6 lg:grid-cols-2"><Glass className="p-6"><div className="flex items-center gap-3 mb-5"><Store size={18} className="text-amber-400"/><h2 className="text-sm font-semibold text-white">Restaurant</h2></div><div className="space-y-3.5">{[["Name","Bella Cucina"],["Address","47 Maximilianstraße, Munich"],["Currency","EUR"],["Tax","19%"],["Timezone","Europe/Berlin"]].map(([l,v])=><div key={l} className="flex justify-between"><span className="text-sm text-zinc-500">{l}</span><span className="text-sm font-medium text-white">{v}</span></div>)}</div><Btn className="w-full mt-5" onClick={()=>toast.add("Saved")}>Save</Btn></Glass><Glass className="p-6"><div className="flex items-center gap-3 mb-5"><Shield size={18} className="text-amber-400"/><h2 className="text-sm font-semibold text-white">Security</h2></div><div className="space-y-3">{[["Two-Factor Auth","TOTP for Owner & Manager"],["Row Level Security","Tenant isolation"],["Rate Limiting","5 / 15min"],["CSP Headers","Nonce-based"],["Audit Trail","Immutable logs"]].map(([l,d])=><div key={l} className="flex items-center justify-between rounded-xl bg-white/[0.02] border border-white/[0.04] p-3.5"><div><p className="text-sm font-medium text-white">{l}</p><p className="text-[11px] text-zinc-600">{d}</p></div><Badge variant="success"><Lock size={10}/>Active</Badge></div>)}</div></Glass><Glass className="lg:col-span-2 p-6"><div className="flex items-center gap-3 mb-5"><UserCog size={18} className="text-amber-400"/><h2 className="text-sm font-semibold text-white">Permissions</h2></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-white/[0.06]"><th className="px-4 py-3 text-left text-zinc-500">Permission</th>{["Owner","Manager","Chef","Server","Cashier","Host"].map(r=><th key={r} className="px-4 py-3 text-center text-zinc-500">{r}</th>)}</tr></thead><tbody>{[["Settings",[1,0,0,0,0,0]],["Staff",[1,1,0,0,0,0]],["Menu",[1,1,1,0,0,0]],["Orders",[1,1,0,1,1,0]],["Payments",[1,1,0,0,1,0]],["Reports",[1,1,0,0,0,0]],["Tables",[1,1,0,1,0,1]],["Inventory",[1,1,1,0,0,0]]].map(([p,r])=><tr key={p} className="border-b border-white/[0.03]"><td className="px-4 py-3 text-zinc-400">{p}</td>{r.map((v,i)=><td key={i} className="px-4 py-3 text-center">{v?<Check size={13} className="mx-auto text-emerald-400"/>:<X size={13} className="mx-auto text-zinc-800"/>}</td>)}</tr>)}</tbody></table></div></Glass></div></div>;

  /* ━━━ Nav ━━━ */
  const nav=[{id:"dashboard",label:"Overview",icon:LayoutDashboard},{id:"orders",label:"Orders",icon:ShoppingBag,badge:active.length||null},{id:"kitchen",label:"Kitchen",icon:ChefHat,badge:orders.filter(o=>["confirmed","preparing"].includes(o.status)).length||null},{id:"pos",label:"Point of Sale",icon:CreditCard},{id:"menu",label:"Menu",icon:UtensilsCrossed},{id:"tables",label:"Floor Plan",icon:Armchair},{id:"reservations",label:"Reservations",icon:CalendarClock,badge:reservations.filter(r=>r.status==="confirmed").length||null},{id:"inventory",label:"Inventory",icon:Package,badge:inventory.filter(i=>i.qty<=i.threshold).length||null},{id:"staff",label:"Team",icon:Users},{id:"analytics",label:"Analytics",icon:BarChart3},{id:"customers",label:"Guests",icon:Heart},{id:"settings",label:"Settings",icon:Settings}];
  const pages={dashboard:Dashboard,orders:Orders,kitchen:Kitchen,pos:POS,menu:Menu,tables:Tables,reservations:Reservations,inventory:Inventory,staff:Staff,analytics:Analytics,customers:Customers,settings:SettingsPage};const P=pages[page]||Dashboard;

  return<><div className="flex h-screen overflow-hidden bg-[#09090b] text-white">
    <aside className={cn("flex flex-col border-r border-white/[0.06] bg-[#09090b] transition-all duration-300 shrink-0",sidebar?"w-[240px]":"w-[68px]")}><div className="flex h-[72px] items-center gap-3.5 border-b border-white/[0.06] px-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-amber-400 to-amber-600 shadow-lg shadow-amber-500/15"><UtensilsCrossed size={20} className="text-white" strokeWidth={1.5}/></div>{sidebar&&<div><p className="text-sm font-bold tracking-tight" style={{fontFamily:"Georgia,serif"}}>Bella Cucina</p><p className="text-[10px] font-medium tracking-[0.15em] uppercase text-zinc-600">Management</p></div>}</div>
      <nav className="flex-1 overflow-y-auto py-4 px-3 space-y-0.5">{nav.map(n=>{const I=n.icon;const a=page===n.id;return <button key={n.id} onClick={()=>setPage(n.id)} className={cn("group flex w-full items-center gap-3 rounded-xl px-3.5 py-2.5 text-[13px] font-medium transition-all duration-200",a?"bg-amber-500/10 text-amber-400":"text-zinc-500 hover:bg-white/[0.04] hover:text-zinc-300",!sidebar&&"justify-center px-0")}><I size={18} strokeWidth={a?2:1.5}/>{sidebar&&<><span className="flex-1 text-left">{n.label}</span>{n.badge&&<span className="flex h-[22px] min-w-[22px] items-center justify-center rounded-lg bg-amber-500/15 px-1.5 text-[10px] font-bold text-amber-400">{n.badge}</span>}</>}</button>})}</nav>
      <div className="border-t border-white/[0.06] p-3"><button onClick={()=>setSidebar(!sidebar)} className="flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-xs text-zinc-600 hover:bg-white/[0.04] hover:text-zinc-400">{sidebar?<PanelLeftClose size={16}/>:<PanelLeft size={16}/>}{sidebar&&"Collapse"}</button></div>
    </aside>
    <div className="flex flex-1 flex-col min-w-0">
      <header className="flex h-[72px] shrink-0 items-center justify-between border-b border-white/[0.06] px-7"><div className="flex items-center gap-2.5 rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-2"><Search size={14} className="text-zinc-600"/><span className="text-xs text-zinc-600">Search...</span><kbd className="ml-6 rounded-md border border-white/[0.06] bg-white/[0.03] px-1.5 py-0.5 text-[10px] text-zinc-600">⌘K</kbd></div><div className="flex items-center gap-4"><span className="text-xs text-zinc-600 font-mono tracking-wider">{new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}</span><button className="relative rounded-xl p-2.5 text-zinc-500 hover:bg-white/[0.04]"><Bell size={18} strokeWidth={1.5}/>{active.length>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-amber-500"><span className="absolute inset-0 rounded-full bg-amber-500 animate-ping opacity-75"/></span>}</button><div className="flex items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-2"><div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-amber-400 to-amber-600 text-[11px] font-bold text-white">{(user||"U")[0].toUpperCase()}</div><div className="hidden sm:block"><p className="text-xs font-medium text-zinc-300">{user}</p><p className="text-[10px] text-zinc-600">Owner</p></div></div><button onClick={()=>{setIsAuth(false);setOrders([]);setTables(seedTables.map(t=>({...t,status:"available",orderId:null,guests:0,server:null,seatedAt:null})))}} className="rounded-xl p-2.5 text-zinc-700 hover:text-red-400"><LogOut size={16} strokeWidth={1.5}/></button></div></header>
      <main className="flex-1 overflow-y-auto p-7"><P/></main>
    </div>
  </div><Toasts toasts={toast.toasts}/><Styles/></>;
}

function MenuForm({item:init,cats,onSave,onCancel}){const[f,setF]=useState({...init});const u=(k,v)=>setF(p=>({...p,[k]:v}));return <div className="space-y-5"><Input label="Name" value={f.name} onChange={e=>u("name",e.target.value)} placeholder="e.g. Risotto ai Funghi"/><div className="grid grid-cols-2 gap-4"><Select label="Category" value={f.catId} onChange={e=>u("catId",e.target.value)}>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select label="Station" value={f.station} onChange={e=>u("station",e.target.value)}>{["grill","pasta","pizza","salad","bar"].map(s=><option key={s}>{s}</option>)}</Select></div><div className="grid grid-cols-3 gap-4"><Input label="Price" type="number" step="0.1" value={f.price} onChange={e=>u("price",+e.target.value)}/><Input label="Cost" type="number" step="0.1" value={f.cost} onChange={e=>u("cost",+e.target.value)}/><Input label="Prep (min)" type="number" value={f.prepTime} onChange={e=>u("prepTime",+e.target.value)}/></div><Input label="Allergens" value={(f.allergens||[]).join(", ")} onChange={e=>u("allergens",e.target.value.split(",").map(s=>s.trim()).filter(Boolean))} placeholder="Gluten, Dairy..."/><div className="flex items-center gap-3"><input type="checkbox" checked={f.available} onChange={e=>u("available",e.target.checked)} className="rounded accent-amber-500"/><span className="text-sm text-zinc-300">Available</span></div><div className="flex gap-3 pt-2"><Btn className="flex-1" onClick={()=>{if(!f.name.trim())return;onSave(f)}}><Save size={14} className="inline mr-1.5"/>{f.id?"Update":"Create"}</Btn><Btn variant="secondary" onClick={onCancel}>Cancel</Btn></div></div>}

function Styles(){return <style>{`@keyframes fade-up{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes toast-in{from{opacity:0;transform:translateY(16px) scale(0.96)}to{opacity:1;transform:translateY(0) scale(1)}}.anim-stagger>*{animation:fade-up 0.5s cubic-bezier(0.16,1,0.3,1) both}.anim-stagger>*:nth-child(1){animation-delay:0ms}.anim-stagger>*:nth-child(2){animation-delay:60ms}.anim-stagger>*:nth-child(3){animation-delay:120ms}.anim-stagger>*:nth-child(4){animation-delay:180ms}.anim-stagger>*:nth-child(5){animation-delay:240ms}.anim-stagger>*:nth-child(6){animation-delay:300ms}.anim-stagger>*:nth-child(7){animation-delay:360ms}::-webkit-scrollbar{width:5px;height:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.06);border-radius:10px}::-webkit-scrollbar-thumb:hover{background:rgba(255,255,255,0.1)}::selection{background:rgba(245,158,11,0.25)}body{background:#09090b;color:#fafafa;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}`}</style>}
